// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'agent.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Agent _$$_AgentFromJson(Map<String, dynamic> json) => _$_Agent(
      id: json['id'] as String?,
      userId: json['user_id'] as String?,
      moniId: json['moni_id'] as String?,
      eligibleLoanId: json['eligible_loan_id'] as String?,
      firstName: json['first_name'] as String?,
      middleName: json['middle_name'] as String?,
      lastName: json['last_name'] as String?,
      nickname: json['nickname'] as String?,
      birthDate: json['birth_date'] as String?,
      gender: json['gender'] as String?,
      businessName: json['business_name'] as String?,
      maritalStatus: json['marital_status'] as String?,
      education: json['education'] as String?,
      houseAddress: json['house_address'] as String?,
      shopAddress: json['shop_address'] as String?,
      lga: json['lga'] as String?,
      city: json['city'] as String?,
      state: json['state'] as String?,
      country: json['country'] as String?,
      phoneNumber: json['phone_number'] as String?,
      emailAddress: json['email_address'] as String?,
      bvn: json['bvn'] as String?,
      hasCreditHistory: json['has_credit_history'] as int?,
      verified: json['verified'] as int?,
      referralLink: json['referral_link'] as String?,
      mediaUrl: json['media_url'] as String?,
      channel: json['channel'] as String?,
      agentRepaymentRate: json['agent_repayment_rate'] as int?,
      bvnVerifiedAfter: json['bvn_verified_after'] as int?,
      loanEnabled: json['loan_enabled'] as int?,
      statusId: json['status_id'] as int?,
      eligibleLoanModifiedAt: json['eligible_loan_modified_at'] as String?,
      createdAt: json['created_at'] as String?,
      modifiedAt: json['modified_at'] as String?,
      capAgentLoan: json['cap_agent_loan'] as int?,
      loanCount: json['loan_count'] as int?,
      recentLoan: json['recent_loan'] == null
          ? null
          : RecentLoan.fromJson(json['recent_loan'] as Map<String, dynamic>),
      suspended: json['suspended'] as bool?,
    );

Map<String, dynamic> _$$_AgentToJson(_$_Agent instance) => <String, dynamic>{
      'id': instance.id,
      'user_id': instance.userId,
      'moni_id': instance.moniId,
      'eligible_loan_id': instance.eligibleLoanId,
      'first_name': instance.firstName,
      'middle_name': instance.middleName,
      'last_name': instance.lastName,
      'nickname': instance.nickname,
      'birth_date': instance.birthDate,
      'gender': instance.gender,
      'business_name': instance.businessName,
      'marital_status': instance.maritalStatus,
      'education': instance.education,
      'house_address': instance.houseAddress,
      'shop_address': instance.shopAddress,
      'lga': instance.lga,
      'city': instance.city,
      'state': instance.state,
      'country': instance.country,
      'phone_number': instance.phoneNumber,
      'email_address': instance.emailAddress,
      'bvn': instance.bvn,
      'has_credit_history': instance.hasCreditHistory,
      'verified': instance.verified,
      'referral_link': instance.referralLink,
      'media_url': instance.mediaUrl,
      'channel': instance.channel,
      'agent_repayment_rate': instance.agentRepaymentRate,
      'bvn_verified_after': instance.bvnVerifiedAfter,
      'loan_enabled': instance.loanEnabled,
      'status_id': instance.statusId,
      'eligible_loan_modified_at': instance.eligibleLoanModifiedAt,
      'created_at': instance.createdAt,
      'modified_at': instance.modifiedAt,
      'cap_agent_loan': instance.capAgentLoan,
      'loan_count': instance.loanCount,
      'recent_loan': instance.recentLoan,
      'suspended': instance.suspended,
    };
